### ISSUE TITLE
version 0.3 doesn't include latest update

### ISSUE THREAD

**Issue by johncruz24** [punksta/fastlane-plugin-xamarin_build#6]
I am trying to use the version 0.3 to build a xamarin app and its doesn't include the latest changes. Is there a way to get that to work? @punksta

**Comment by punksta** [comment]
you can try it like this:
```
gem 'fastlane-plugin-xamarin_build', :git => 'https://github.com/punksta/fastlane-plugin-xamarin_build'
```

**Comment by johncruz24** [comment]
thanks that worked for me.
